#ifndef LIBKEYFINDER_GLOBAL_H
#define LIBKEYFINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBKEYFINDER_LIBRARY)
#  define LIBKEYFINDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBKEYFINDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBKEYFINDER_GLOBAL_H
